import { AKGIcon } from "@/app/components/AKGIcon";
import { Heading } from "@/app/components/blog/Heading";
import { Link } from "@/app/components/blog/Link";
import { Paragraph } from "@/app/components/blog/Paragraph";
import { Title } from "@/app/components/blog/Title";
import Image from "next/image";

export default function OnePercentAI() {
  return (
    <main className="mx-auto flex min-h-[calc(100vh-theme(space.16))] max-w-[740px] flex-col content-center bg-white p-6 dark:bg-black md:p-10 lg:p-8 lg:px-16 lg:py-12">
      <Title title="1% AI" />
      <Paragraph>
        In the beginning of 2025, the engineering team at <Link href="https://www.thelangstonco.com" text="The Langston Company" /> was like many
        others. We were skeptical of the grandiose claims about AI&apos;s coding
        abilities from major AI companies and LinkedIn influencers. Every day, we
        saw headlines and blog posts claiming that &quot;coding is dead&quot; and
        &quot;AI will replace all software engineers by the end of the
        decade.&quot;
      </Paragraph>
      <Paragraph>
        We would try using Copilot or ChatGPT to build new features, and it
        consistently felt like a smoke screen. To us, AI was mostly useful for
        generating Stack Overflow&ndash;style answers tailored to our questions.
        That&apos;s a helpful tool, but not one that felt like it would
        revolutionize software engineering.
      </Paragraph>
      <Heading id="one-percent">1%</Heading>
      <Paragraph>
        In early 2025, we were writing between 1%&ndash;10% of our production
        code using AI. We primarily used Copilot in our editors (VSCode and
        WebStorm), along with ChatGPT and Claude Code in the browser. We
        provided each tool with a few paragraphs of context detailing what our
        company does, the programming languages we use, example database schemas
        and migrations, our tech stack, and some coding style and rules.
      </Paragraph>
      <Paragraph>
        Copilot understood our repositories best due to its deep integration
        with our editors. It could analyze each codebase independently and adapt
        to our style.
      </Paragraph>
      <Heading id="workflow">Workflow</Heading>
      <Paragraph>
        Our typical workflow started with planning new features at the database
        layer. Then we moved to API endpoints, and finally to the frontend. We
        would occasionally use an LLM to help design schemas, but most of that
        work was still done by hand. In our experience, LLMs were good at
        writing query languages, so we used them to generate schema and
        migration files. The results were usually close based on our provided
        context and a few pasted examples, but still required manual cleanup. We
        would copy and paste the output into our editor or let Copilot apply
        changes. It worked, but it wasn&apos;t a great experience. It felt like
        a slightly better version of Stack Overflow.
      </Paragraph>
      <Paragraph>
        We would then move on to the API. We scaffolded endpoints by hand and
        wrote most of the service layer ourselves. Good old-fashioned software
        engineering. We used LLMs for complex queries, debugging, and writing
        unit tests. Still, only a few lines per PR were actually generated by
        AI.
      </Paragraph>
      <Paragraph>
        Lastly, we built the frontend to support the new feature. Our stack
        includes React, Next.js, TypeScript, and ShadCN. This integrates well
        with Vercel&apos;s ecosystem, especially v0. We would prototype more
        complex UI in v0 by iterating through prompts. The generated code
        wasn&apos;t great and was often difficult to integrate, so we treated it
        more as a design tool. We&apos;d take the UI/UX direction from the
        mockups and build proper components ourselves.
      </Paragraph>
      <Heading id="thoughts">Thoughts</Heading>
      <Paragraph>
        This was a standard web development workflow for over a decade: define
        your schema, build your CRUD endpoints, and create a UI that interacts
        with those layers. We used AI tools around the edges, but we didn&apos;t
        trust them with anything substantial. We believed the best, and really
        the only, way to write software was hands-on, using AI only for trivial
        tasks. It helped automate unit tests, iterate on simple UI, or answer
        obscure questions about things like CSS properties.
      </Paragraph>
      <Paragraph>
        That mental model held up for most of the year. AI was a tool, not a
        transformational technology. Around October of 2025, we started
        experimenting and studying how experienced developers were using these
        tools in practice.
      </Paragraph>
      <Paragraph>
        A year later, we&apos;ve completely changed how we write software.
        We&apos;ve gone from 1% to 99%. Agentic AI workflows have changed how
        we work, how we solve problems, and how we think about software.
      </Paragraph>
      <div className="mt-10 flex items-center gap-2 border-t border-white-900 pt-6 text-xs text-white-500">
        <span>Written by me. Proofread by</span>
        <span>Claude Sonnet 4.6</span>
        <Image
          src="/500px-Claude_AI_symbol.png"
          alt="Claude"
          width={16}
          height={16}
          className="opacity-70"
        />
      </div>
      <AKGIcon className="mt-8" />
    </main>
  );
}
